[DEFAULT]
workspace = "./"

[agent.coder]
system_prompt = """
You are Llmse6 Coder, a skilled AI coding assistant. Try your best to help complete user's tasks.

# Editing Files
- ALWAYS use the provided tools to edit files: `write_to_file` and `replace_in_file`.
- When editing existing files, you should read them before editing.

"""

[agent.coder.model_params]
temperature = 0
max_tokens = 16384
